import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import { Header } from "@/app/header";
import { SessionProvider } from "next-auth/react";
import { AppKnockProviders } from "@/app/knock-provider";
import { ThemeProvider } from "@/components/themeProvider";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SessionProvider>
            <AppKnockProviders>
              <Header />
              <div className="container h-screen  mx-auto py-12">
                {children}
              </div>
            </AppKnockProviders>
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
